<?php include( 'header.php' ); ?>

<div class="container">
    <table id="table">
        <thead>
            <tr>
                <th>No</th>
                <th>Period</th>
                <th>Description</th>
                <th>Due Date</th>
                <th>Charge (Rp)</th>
                <th>Payment (Rp)</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody id="tableContent">
            <tr>
                <td>1</td>
                <td>Germany</td>
                <td>Germany</td>
                <td>Germany</td>
                <td>Germany</td>
                <td>Germany</td>
                <td>Germany</td>
            </tr>
            <tr>
                <td>1</td>
                <td>Germany</td>
                <td>Germany</td>
                <td>Germany</td>
                <td>Germany</td>
                <td>Germany</td>
                <td>Germany</td>
            </tr>
            <tr>
                <td>1</td>
                <td>Germany</td>
                <td>sdnsk</td>
                <td>Germany</td>
                <td>Germany</td>
                <td>Germany</td>
                <td>Germany</td>
            </tr>
            <tr>
                <td>1</td>
                <td>Germany</td>
                <td>tre</td>
                <td>Germany</td>
                <td>Germany</td>
                <td>Germany</td>
                <td>Germany</td>
            </tr>
            <tr>
                <td>1</td>
                <td>Germany</td>
                <td>Germany</td>
                <td>Germany</td>
                <td>Germany</td>
                <td>Germany</td>
                <td>Germany</td>
            </tr>
            <tr>
                <td>1</td>
                <td>Germany</td>
                <td>Germany</td>
                <td>Germany</td>
                <td>Germany</td>
                <td>Germany</td>
                <td>Germany</td>
            </tr>
            <tr>
                <td>1</td>
                <td>Germany</td>
                <td>Germany</td>
                <td>Germany</td>
                <td>Germany</td>
                <td>Germany</td>
                <td>Germany</td>
            </tr>
            <tr>
                <td>1</td>
                <td>Germany</td>
                <td>Germany</td>
                <td>Germany</td>
                <td>Germany</td>
                <td>Germany</td>
                <td>Germany</td>
            </tr>
            <tr>
                <td>1</td>
                <td>Germany</td>
                <td>Germany</td>
                <td>Germany</td>
                <td>Germany</td>
                <td>Germany</td>
                <td>Germany</td>
            </tr>
            <tr>
                <td>1</td>
                <td>Germany</td>
                <td>Germany</td>
                <td>Germany</td>
                <td>Germany</td>
                <td>Germany</td>
                <td>Germany</td>
            </tr>
            <tr>
                <td>1</td>
                <td>Germany</td>
                <td>Germany</td>
                <td>Germany</td>
                <td>Germany</td>
                <td>Germany</td>
                <td>Germany</td>
            </tr>
            <tr>
                <td>1</td>
                <td>Germany</td>
                <td>Germany</td>
                <td>Germany</td>
                <td>Germany</td>
                <td>Germany</td>
                <td>Germany</td>
            </tr>
            <tr>
                <td>1</td>
                <td>Germany</td>
                <td>Germany</td>
                <td>Germany</td>
                <td>Germany</td>
                <td>Germany</td>
                <td>Germany</td>
            </tr>
            <tr>
                <td>1</td>
                <td>Germany</td>
                <td>Germany</td>
                <td>Germany</td>
                <td>Germany</td>
                <td>Germany</td>
                <td>Germany</td>
            </tr>
            <tr>
                <td>1</td>
                <td>Germany</td>
                <td>Germany</td>
                <td>Germany</td>
                <td>Germany</td>
                <td>Germany</td>
                <td>Germany</td>
            </tr>
            <tr>
                <td>1</td>
                <td>Germany</td>
                <td>Germany</td>
                <td>Germany</td>
                <td>Germany</td>
                <td>Germany</td>
                <td>Germany</td>
            </tr>
            <tr>
                <td>1</td>
                <td>Germany</td>
                <td>Germany</td>
                <td>Germany</td>
                <td>Germany</td>
                <td>Germany</td>
                <td>Germany</td>
            </tr>
        </tbody>
    </table>
</div>

<?php include( 'footer.php' ); ?>

<script type="text/javascript">
    $(document).ready(function(){
    $('#table').DataTable();
});
</script>